InseeFr/Lunatic-Model

- .travis.yml
- docs/fr/usage/README.md
- pom.xml
- src/test/java/fr/insee/lunatic/test/TranslatorsTest.java
- src/test/resources/examples/xmlf-2-jsonf/in.xml
- src/test/resources/examples/xmlf-2-jsonf/out.json
- src/test/resources/examples/xmlh-2-jsonf/in.xml
- src/test/resources/examples/xmlh-2-jsonf/out.json
- src/test/resources/examples/xmlh-2-jsonh/in.xml
- src/test/resources/examples/xmlh-2-jsonh/out.json
- src/test/resources/examples/xmlh-2-xmlf/in.xml
- src/test/resources/examples/xmlh-2-xmlf/out.xml
- update files for test
- fix encoding issue with maven test
- add test phase in travis
> Add test in travis

- pom.xml
- src/main/java/fr/insee/lunatic/Constants.java
- src/main/java/fr/insee/lunatic/utils/Modele.java
- src/main/java/fr/insee/lunatic/utils/SchemaValidator.java
- src/main/resources/xsd/LunaticModel.xsd
- src/main/resources/xsd/LunaticModelFlat.xsd
- src/test/java/fr/insee/lunatic/main/DummyTestSchemaValidatorF.java
- src/test/java/fr/insee/lunatic/main/DummyTestSchemaValidatorH.java
- src/test/java/fr/insee/lunatic/main/DummyTestXMLLunatic2JSONF.java
- src/test/java/fr/insee/lunatic/test/ValidatorTest.java
- src/test/resources/dummy/form.xml
- src/test/resources/dummy/form_flat.xml
- src/test/resources/examples/xmlf-2-jsonf/out.json
- src/test/resources/examples/xmlh-2-jsonf/out.json
- src/test/resources/examples/xmlh-2-jsonh/out.json
- add validator utils function
- update order of components in xsd schema
> Update XSD schema

- pom.xml
- src/main/resources/xsd/LunaticModel.xsd
- src/main/resources/xsd/LunaticModelFlat.xsd
- upgrade from 2.2.2 to 2.2.3 version
> Add controls to the model

- pom.xml
- src/main/resources/xsd/LunaticModel.xsd
- src/main/resources/xsd/LunaticModelFlat.xsd
Adding CODECARD in enumeration for DeclarationType to support use of codecard instructions
> Develop update for codecard

- pom.xml
- src/main/resources/xsd/LunaticModel.xsd
- src/main/resources/xsd/LunaticModelFlat.xsd
- src/main/resources/xslt/json-cleaner.xsl
In LunaticModel and LunaticModelFlat xsd :
- Modification for suggesters (including adding synonyms)
- Adding a field inFilter for calculated variables
> Suggester and inFilter in model xsds

- src/main/java/fr/insee/lunatic/conversion/JSONCleaner.java
- src/main/java/fr/insee/lunatic/conversion/JSONDeserializer.java
- src/main/java/fr/insee/lunatic/conversion/JSONSymLinksCleaner.java
- src/test/java/fr/insee/lunatic/test/JSONSymLinksCleanerTest.java
- src/test/java/fr/insee/lunatic/test/PairwiseTest.java
- src/test/resources/pairwise/pairwise-flat.json
- src/test/resources/pairwise/pairwise-flat.xml
- src/test/resources/pairwise/pairwise-hierarchical-test.xml
`SymLinks` object modified in the model: the "LINKS" name is not fixed.
`JSONSymLinksCleaning` class updated.
> fix: Dev pairwise update cleaning with variable SymLink

- .github/workflows/create-release.yml
- .github/workflows/create-snapshot.yml
- .github/workflows/tests.yml
* delete unused step in create release ci
* only deploy snapshot when the deploy-snapshot label is set
> ci: fix minor issues

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/SuggesterQueryParserParams.java
- src/main/java/fr/insee/lunatic/model/flat/SuggesterType.java
- `"stemmer"` was missing in fields query params
- `"meloto"` was missing
> fix(suggester): add missing properties

- .github/dependabot.yml
- .github/workflows/create-release.yml
- .github/workflows/create-snapshot.yml
- .github/workflows/tests.yml
- pom.xml
- java 17 to 21
- add dependabot config
> build: java 21

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/CleanedVariableEntry.java
- src/main/java/fr/insee/lunatic/model/flat/CleaningEntry.java
- src/main/java/fr/insee/lunatic/model/flat/CleaningType.java
- src/main/java/fr/insee/lunatic/model/flat/CleaningVariableEntry.java
- src/test/java/fr/insee/lunatic/conversion/CleaningSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/JsonDeserializerTest.java
Almost a feature: cleaning was previsouly modeled as a list of objects.
> refactor: cleaning modeling

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ResizingEntry.java
- src/main/java/fr/insee/lunatic/model/flat/ResizingIterationEntry.java
- src/main/java/fr/insee/lunatic/model/flat/ResizingPairwiseEntry.java
- src/main/java/fr/insee/lunatic/model/flat/ResizingType.java
- src/test/java/fr/insee/lunatic/conversion/ResizingSerializationTest.java
Analog to what has been done for cleaning
> refactor: resizing modeling

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/MissingEntry.java
- src/main/java/fr/insee/lunatic/model/flat/MissingType.java
- src/test/java/fr/insee/lunatic/conversion/MissingSerializationTest.java
Missing block modeling.
I didn't add any logic (like methods to create reverse entry/entries)
> refactor: missing block modeling

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentTypeEnum.java
- src/main/java/fr/insee/lunatic/model/flat/DeclarationTypeEnum.java
- src/main/java/fr/insee/lunatic/model/flat/Question.java
- src/test/java/fr/insee/lunatic/conversion/QuestionSerializationTest.java
- src/test/java/fr/insee/lunatic/utils/TestUtils.java
- src/test/resources/input-question.json
Lunatic spec: https://inseefr.github.io/Lunatic-DSFR/storybook/?path=/docs/components-question--documentation
> feat: question component

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentTypeEnum.java
- src/main/java/fr/insee/lunatic/model/flat/Duration.java
- src/main/java/fr/insee/lunatic/model/flat/DurationFormat.java
- src/main/java/fr/insee/lunatic/model/flat/Question.java
- src/test/java/fr/insee/lunatic/conversion/DurationSerializationTest.java
- src/test/resources/duration-hours-minutes.json
- src/test/resources/duration-years-months.json
> feat: duration component

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/variable/CalculatedVariableType.java
- src/main/java/fr/insee/lunatic/model/flat/variable/VariableDimension.java
- src/main/java/fr/insee/lunatic/model/flat/variable/VariableType.java
- src/test/java/fr/insee/lunatic/conversion/variable/CalculatedVariableSerializationTest.java
Add a `"dimension"` property on variable objects.
> feat: variables dimension

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/BodyLine.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentTypeEnum.java
- src/main/java/fr/insee/lunatic/model/flat/Question.java
- src/main/java/fr/insee/lunatic/model/flat/Text.java
- src/test/java/fr/insee/lunatic/conversion/TableSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/TextSerializationTest.java
Add `"Text"` component, that can be used as a regular component, within a question component, or as a table cell.
> feat: text component

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/PairwiseLinks.java
> fix: symlinks default values

- src/main/java/fr/insee/lunatic/model/flat/LabelTypeEnum.java
- src/test/java/fr/insee/lunatic/conversion/LabelSerializationTest.java
> feat: txt label type

- src/main/java/fr/insee/lunatic/model/flat/Accordion.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentTypeEnum.java
- src/main/java/fr/insee/lunatic/model/flat/Question.java
- src/test/java/fr/insee/lunatic/conversion/AccordionSerializationTest.java
> feat: accordion component

- src/main/java/fr/insee/lunatic/conversion/UnitDeserializer.java
- src/main/java/fr/insee/lunatic/conversion/UnitSerializer.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/InputNumber.java
- src/test/java/fr/insee/lunatic/conversion/InputNumberSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/UnitDeserializerTest.java
- src/test/java/fr/insee/lunatic/conversion/UnitSerializerTest.java
> feat: label object for input number unit

- src/main/java/fr/insee/lunatic/model/flat/Pagination.java
- src/main/java/fr/insee/lunatic/model/flat/Questionnaire.java
- src/test/java/fr/insee/lunatic/conversion/PaginationSerializationTest.java
> refactor: enum for questionnaire pagination

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/Suggester.java
- src/test/java/fr/insee/lunatic/conversion/SuggesterSerializationTest.java
> feat(suggester): option responses

- .github/workflows/create-release.yml
- .github/workflows/create-snapshot.yml
- .github/workflows/tests.yml
- pom.xml
- src/test/java/fr/insee/lunatic/conversion/data/JsonToXmlDataTest.java
Java 17 pour l'instant, 21 la prochaine fois 🙃
> build: java 17

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ControlContextType.java
- dependencies update
- #272 
@lunatic-people je vous ping en reviewers pour info
> V3 next: 3.15.3

- pom.xml
- src/main/java/fr/insee/lunatic/conversion/JsonDeserializer.java
- src/main/java/fr/insee/lunatic/model/flat/ArbitraryType.java
- src/main/java/fr/insee/lunatic/model/flat/Suggester.java
- src/test/java/fr/insee/lunatic/conversion/SuggesterSerializationTest.java
cf.
- InseeFr/Lunatic#906
En particulier : 
https://github.com/InseeFr/Lunatic/pull/906/files#diff-3073418badd32939818d4f9f49aaf6b8609a9a4ab3b4877271bcf9fa5eb711ff
\+ un peu de refacto sur le `JsonDeserializer` (méthode dégueu passée en _deprecated_)
> feat(suggester): arbitrary response

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/Datepicker.java
- src/main/java/fr/insee/lunatic/model/flat/Dropdown.java
- src/main/java/fr/insee/lunatic/model/flat/Duration.java
- src/main/java/fr/insee/lunatic/model/flat/Input.java
- src/main/java/fr/insee/lunatic/model/flat/InputNumber.java
- src/main/java/fr/insee/lunatic/model/flat/Question.java
- src/main/java/fr/insee/lunatic/model/flat/Radio.java
- src/main/java/fr/insee/lunatic/model/flat/Suggester.java
- src/main/java/fr/insee/lunatic/model/flat/Textarea.java
- src/test/java/fr/insee/lunatic/conversion/DurationSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/InputSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/QuestionSerializationTest.java
- src/test/resources/duration-hours-minutes.json
- src/test/resources/duration-years-months.json
- `"isMandatory"` attribute
- dependencies update
> next: 4.2.0

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/CheckboxBoolean.java
- src/main/java/fr/insee/lunatic/model/flat/CheckboxOne.java
- src/main/java/fr/insee/lunatic/model/flat/InputNumber.java
Complète: https://github.com/InseeFr/Lunatic-Model/pull/285
> fix: mandatory attribute

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ComponentSimpleResponseType.java
Ajout de mandatory dans l'interface pour les composants avec une réponse simple.
> refactor: add mandatory interface for single response components

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/BodyCell.java
- src/main/java/fr/insee/lunatic/model/flat/Boundaries.java
- src/main/java/fr/insee/lunatic/model/flat/NumberBoundaries.java
- src/main/java/fr/insee/lunatic/model/flat/StringBoundaries.java
- src/test/java/fr/insee/lunatic/conversion/BodyCellSerializationTest.java
- min/max en string pour les body cell de type date/duration
- montée de version jackson
> Next: 5.2.0

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/BodyCell.java
- src/test/java/fr/insee/lunatic/conversion/RosterForLoopSerializationTest.java
- Ajout de **conditionReadOnly** pour mettre en lecture seule (readonly) certaines cases d’un tableau selon une formule VTL.
- + tests.
> Feat: readonly case
