InseeFr/Lunatic-Model

- .gitignore
- pom.xml
> Support Jdk 11

- pom.xml
- src/main/resources/xsd/LunaticModel.xsd
- src/main/resources/xsd/LunaticModelFlat.xsd
- src/main/resources/xslt/json-cleaner.xsl
Workaround for suggesters : the tag for field rules can be 'rules' if soft or 'rulesA' if array, then it is changed in json-cleaner.xsl step
Lunatic-model version is bumped to 2.2.8
> Workaround for suggesters and rules tag of field

- pom.xml
Bumping version of log4j from 2.11.0 to 2.16.0 (following disclosure of log4shell vulnerability)
> Bump dependency of log4j to 2.16.0, lunatic-model to 2.2.9

- pom.xml
- src/main/resources/xsd/LunaticModel.xsd
- src/main/resources/xsd/LunaticModelFlat.xsd
Les contrôles de formats sont désormais portés par le modèle (Eno les ajoute à partir des métadonnées décrites dans Pogues. Exemple : min, max, nombre de décimales). 
Les contrôles de format (standardisés) sont les suivants : 
- Pour les nombres : vérification du nombre de décimales et des bornes
- Pour les dates : vérification des bornes
Un typage de contrôle `typeOfControl` a été ajouté. Les valeurs possibles sont : 
- `FORMAT` (contrôle de format ajouté par Eno non modifiable) 
- `CONSISTENCY` (contrôle métier saisi dans Pogues)
Exemple : 
***Lunatic V2 :*** 
```json
"controls" : 
[ 
{ "id" : "k5nw0w05-format-borne-inf-sup",
"typeOfControl" : "FORMAT",
"criticality" : "ERROR",
"control" : 
{ "value" : "not(not(isnull(DURATIONH)) and (0.00>DURATIONH or 70.00<DURATIONH))",
"type" : "VTL" …
```
> Dev lunatic format control type

- pom.xml
- src/main/resources/xsd/LunaticModel.xsd
- src/main/resources/xsd/LunaticModelFlat.xsd
If [Lunatic spec on "pairwise links"](https://github.com/InseeFr/Lunatic/blob/v2-master/src/stories/pairwise/links.json) is up-to-date, "PairwiseLinks" requires a "components" list.
This list is currently missing (maybe just an oversight during "symLinks" implementation https://github.com/InseeFr/Lunatic-Model/commit/969c3e9a2f0a88c79ad84d20b4cc85641fbe0954).
> [Dev pairwise] Restore "components" in "PairwiseLinks"

- src/main/java/fr/insee/lunatic/conversion/JSONSymLinksCleaner.java
`source` & `target` attributes in `symLinks` object has been set to `string` type.
Fix: 
- An unexpected effect of this in java during json values to string cast.
- Manage the case of `"null"` string values after XML to JSON conversion.
> fix: superfluous quote marks in symLinks cleaning

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/BodyCell.java
Use `ComponentTypeEnum` instead of `String` for the "componentType" property in "BodyCell" class.
Only changes Java classes, no impact on the serialization of valid questionnaires.
(NB: we should find a way to make something cleaner than "BodyCell" (make polymorphism by re-using proper objects like LabelType or ComponentType) later on.)
> refactor: use proper enum in BodyCell componentType

- pom.xml
- src/main/java/fr/insee/lunatic/conversion/FieldSynonymsSerializer.java
- src/main/java/fr/insee/lunatic/conversion/SymLinksSerializer.java
- src/main/java/fr/insee/lunatic/model/flat/FieldSynonyms.java
- src/main/java/fr/insee/lunatic/model/flat/SuggesterField.java
- src/main/java/fr/insee/lunatic/model/flat/SuggesterType.java
- src/test/java/fr/insee/lunatic/conversion/FieldSynonymsSerializationTest.java
Previously, synonyms in fields of suggesters were (de-)serialized like this :
```json
{
"synonyms": [
{
"source": "some word",
"target": ["synonym 1", "synonym 2"]
},
{
"source": "some other word",
"target": ["..."]
}
]
}
```
yet Lunatic expects something like this ("dynamic" keys):
```json
{
"synonyms": {
"some word": ["synonym 1", "synonym 2"]
"some other word": ["..."]
}
}
```
- fix `"synonyms"` serialization
- add tests on this
- don't serialize `"rules"` or `"stopWords"` if the list is empty
> fix: suggester synonyms serialization

- pom.xml
- src/main/java/fr/insee/lunatic/conversion/FieldRulesSerializer.java
- src/main/java/fr/insee/lunatic/conversion/FieldSynonymsSerializer.java
- src/main/java/fr/insee/lunatic/model/flat/FieldRules.java
- src/main/java/fr/insee/lunatic/model/flat/SuggesterField.java
- src/test/java/fr/insee/lunatic/conversion/FieldRulesSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/FieldSynonymsSerializationTest.java
Somewhat linked to:
- InseeFr/Lunatic#784
Patch to Lunatic-Model to make the serialization of the `"rules"` property as either string or array of string possible.
> fix: suggester field rules

- pom.xml
- src/main/resources/xslt/json-cleaner.xsl
- src/test/java/fr/insee/lunatic/test/PairwiseTest.java
- src/test/resources/pairwise/label-type-issue/form-hierarchical.xml
The xslt sheet used in `JSONCleaner` was removing the `"type"` property in `"xAxisIterations"` and `"yAxisIterations"` labels of the pairwise component.
> fix: missing label type in pairwise x and y axis iterations

- pom.xml
- src/main/java/fr/insee/lunatic/conversion/JsonDeserializer.java
- src/main/java/fr/insee/lunatic/model/flat/SuggesterType.java
- src/test/java/fr/insee/lunatic/conversion/SuggesterTypeSerializationTest.java
`"version"` property in `"suggesters"` configuration was typed as a String. It should be an integer for Lunatic.
Changed type to integer. I used java `BigInteger` since it is what's used everywhere in the model, yet I think we should change all these to simple `Integer` someday.
> fix(suggesters): change version type to integer

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/Suggester.java
The `storeName` property only concerns the Suggester component.
Yet in Eno, both integrated suggester and  suggester specific treatment exist. In the specific treatment case, it makes it easier to have the store name at ComponentType level for technical reason.
> refactor: temporary move storeName at ComponentType level

- src/main/java/fr/insee/lunatic/model/flat/ControlContextType.java
- src/main/java/fr/insee/lunatic/model/flat/ControlCriticalityEnum.java
- src/main/java/fr/insee/lunatic/model/flat/ControlType.java
- src/main/java/fr/insee/lunatic/model/flat/ControlTypeEnum.java
Having both `"typeOfControl"` and `"type"` properties in the `"control"` object is weird, we might do some renaming of these props at some point, yet it's how it's done in Lunatic for now.
https://github.com/InseeFr/Lunatic/blob/825b7096760bf3d866fad7f52508b3e233cca30b/src/type.source.ts#L386
> fix: add 'type' property for controls

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/variable/CalculatedVariableType.java
- src/test/java/fr/insee/lunatic/conversion/variable/CalculatedVariableSerializationTest.java
cf. 
- InseeFr/Lunatic#1063
The `shapeFrom` property of calculated variable objects is now a list of strings.
Done it in a backward compatible way:
- in Lunatic-Model API: `String getShapeFrom()` and `void setShapeFrom(String responseName)` are deprecated but still available
- in the deserialization feature: a string is allowed for the `"shapeFrom"` in json source
Introduced `List<String> getShapeFromList()` and `void setShapeFrom(List<String> responseNames)` in the API.
Serialization of `"shapeFrom"` as a string is no longer possible from this version.
> feat: shape from list in calculated variables

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/BodyCell.java
- src/main/java/fr/insee/lunatic/model/flat/CheckboxGroup.java
- src/main/java/fr/insee/lunatic/model/flat/CheckboxOne.java
- src/main/java/fr/insee/lunatic/model/flat/Dropdown.java
- src/main/java/fr/insee/lunatic/model/flat/HeaderType.java
- src/main/java/fr/insee/lunatic/model/flat/Option.java
- src/main/java/fr/insee/lunatic/model/flat/Radio.java
- src/main/java/fr/insee/lunatic/model/flat/ResponseCheckboxGroup.java
- src/test/java/fr/insee/lunatic/conversion/CheckboxGroupSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/CheckboxOneSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/RadioSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/ResponseCheckboxGroupTest.java
- InseeFr/Lunatic#1071
- feat: add condition filter in option object for unique choice components (radio, checkbox one and dropdown) and in response object for multiple choice component (checkbox group)
- refactor: rename unique choice option and multiple choice response objects (plural was misleading, see below)
- docs: add javadoc in response checkbox group object
- test: fix typo in checkbox group serialization test
⚠️ minor breaking change in Lunatic-Model java API:
- `Options` ➡️ `Option`
- `ResponsesCheckboxGroup` ➡️ `ResponseCheckboxGroup`
(This change has no impact on serialization or deserialization.)
> feat: condition in multiple choice options

- src/main/java/fr/insee/lunatic/model/flat/ComponentPosition.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/test/java/fr/insee/lunatic/conversion/AccordionSerializationTest.java
cf.
https://github.com/InseeFr/Lunatic/issues/995#issuecomment-2154361572
Add a `"position"` property in Lunatic components.
This property can have two values for now: `"default"` and `"bottom"`.
The idea of `"default"` is to be equivalent as `null`, but being explicit (i.e. a null value, or the absence of the position property is implicitely equivalent as the "default" value).
> feat: component position property

- docs/fr/components/Table.md
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/RosterForLoop.java
- src/main/java/fr/insee/lunatic/model/flat/Table.java
Removed in docs and marked as for removal in the code.
> refactor: mark table positioning property as 'for removal'

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/BodyCell.java
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
The `"optionResponses` property was missing in the `BodyCell` object.
cf. 
- https://github.com/InseeFr/Eno/issues/1046#issuecomment-2416027625
> fix: add option responses in table cell object

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/BodyCell.java
- src/test/java/fr/insee/lunatic/conversion/BodyCellSerializationTest.java
Ajout/correctif suite à : 
- #264 
@alicela @loichenninger @alexisszmundy Je sais pas si vous lisez cette info dans les questionnaires Lunatic mais le cas échéant ça peut vous intéresser.
> fix: unit objects in body cells

- pom.xml
- src/main/java/fr/insee/lunatic/conversion/variable/CollectedVariableValuesDeserializer.java
- src/main/java/fr/insee/lunatic/model/flat/variable/CollectedVariableValues.java
- src/test/java/fr/insee/lunatic/conversion/variable/CollectedVariableSerializationTest.java
- Suppression des modalités non valorisées de la propriété "values" (EDITED, FORCED, INPUTTED, PREVIOUS) aux emplacements adéquats.
- Ajustement en conséquence des tests liés à ces changements.
PS : je n'ai pas trouvé l'emplacement pour modifier la version.
> refactor!: remove unused edited forced previous etc values

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/Duration.java
- src/test/java/fr/insee/lunatic/conversion/DurationSerializationTest.java
- src/test/resources/duration-hours-minutes.json
- src/test/resources/duration-years-months.json
- Ajout des paramètres min et max dans Duration au format String (les contrôles seront faits ensuite dans Eno pour vérifier qu'on ait bien le format d'origine).
- Pour les dates, les paramètres étaient déjà présents, mais le format ne semble pas "utilisé" ou existant : j'ai laissé tel quel, c'est  réalisé dans Eno il me semble.
- Ajout de lignes dans les tests en mettant des min et max dans Duration.
> Feat(controls): duration min max 

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ComponentType.java
- src/main/java/fr/insee/lunatic/model/flat/Datepicker.java
- src/main/java/fr/insee/lunatic/model/flat/Dropdown.java
- src/main/java/fr/insee/lunatic/model/flat/Duration.java
- src/main/java/fr/insee/lunatic/model/flat/Input.java
- src/main/java/fr/insee/lunatic/model/flat/InputNumber.java
- src/main/java/fr/insee/lunatic/model/flat/Question.java
- src/main/java/fr/insee/lunatic/model/flat/Radio.java
- src/main/java/fr/insee/lunatic/model/flat/Suggester.java
- src/main/java/fr/insee/lunatic/model/flat/Textarea.java
- src/test/java/fr/insee/lunatic/conversion/DurationSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/InputSerializationTest.java
- src/test/java/fr/insee/lunatic/conversion/QuestionSerializationTest.java
- src/test/resources/duration-hours-minutes.json
- src/test/resources/duration-years-months.json
Jusqu'ici, on n'avait pas de concept/fonctionnalité de "réponse obligatoire" dans [Lunatic](https://github.com/InseeFr/Lunatic).
On avait cependant une propriété `"mandatory"` qui traînait dans Luantic-Model (et qu'on doit trouver dans certains source.json de test ou autre).
Désormais, on veut cette fonctionnalité côté Lunatic, pour l'instant pour les **questions à réponse simple** (texte, nombre, date, durée, choix unique).
➡️ propriété `"isMandatory"` pour les composants de question correspondant.
- suppression de `mandatory` au niveau de `ComponentType` (tous les composants ne sont pas concernés par cette prop, du moins pas pour l'instant).
- ajout d'une property `"isMandatory"` pour le composant `"Question"` (concept de **_question obligatoire_**)
- ajoute d'une property …
> feat: mandatory prop for single response components

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/ControlTypeEnum.java
cf.
- InseeFr/Eno#1260
Les contrôles pour les questions obligatoires on un comportement spécifique (notamment dans l'orchestrateur Queen), donc Lunatic a besoin d'une métadonnée pour distinguer ces types de contrôles.
> fix(mandatory control): add 'type of control' metadata

- pom.xml
- src/main/java/fr/insee/lunatic/model/flat/articulation/Articulation.java
- src/test/java/fr/insee/lunatic/conversion/ArticulationSerializationTest.java
Partout dans le modèle où on a une liste, elle est initialisée à l'instanciation, je l'ajoute pour la props items de l'articulation pour me simplifier la vie dans Eno.
Quand on supprimera le setter dans une future release, on pourra passer la liste en `final`.
> refactor(articulation): instantiate items list
